arch: amd64

language: java

jdk:
  - openjdk11

env:
  - CI=false
  - SONAR_PROJECT_ID=com.spa.react:spa-react

services: 
  - docker

before_install:
  - sudo apt-get install jq
  - ./sonar/build_run_container.sh
  
install: true

script:
  - docker ps -a
  - ./sonar/start_quality_scan.sh

after_script:
  - ./sonar/kill_container.sh

cache:
  directories:
    - $HOME/.m2
