arch: amd64

language: java

jdk:
  - openjdk11

env:
  - CI=false

sudo: false

services: 
  - docker

before_install:
  - docker build -t sonarqube-aem -f sonar/Dockerfile .
  - docker run -it -d -p 9000:9000 sonarqube-aem
  
install: mvn clean install -DskipTests

script:
  - docker ps -a
  - mvn clean verify sonar:sonar

after_script:
  - docker ps | grep sonarqube-aem | awk '{print $1}' | xargs docker kill
